// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0

// Code generated by generators/singular-data-source/main.go; DO NOT EDIT.

package vpn_test

import (
	"regexp"
	"testing"

	"github.com/byteplus-sdk/terraform-provider-bytepluscc/internal/acctest"
	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
)

func TestAccByteplusVPNCustomerGatewayDataSource_basic(t *testing.T) {
	td := acctest.NewTestData(t, "Byteplus::VPN::CustomerGateway", "bytepluscc_vpn_customer_gateway", "test")

	td.DataSourceTest(t, []resource.TestStep{
		{
			Config:      td.EmptyDataSourceConfig(),
			ExpectError: regexp.MustCompile("Missing required argument"),
		},
	})
}

func TestAccByteplusVPNCustomerGatewayDataSource_NonExistent(t *testing.T) {
	td := acctest.NewTestData(t, "Byteplus::VPN::CustomerGateway", "bytepluscc_vpn_customer_gateway", "test")

	td.DataSourceTest(t, []resource.TestStep{
		{
			Config:      td.DataSourceWithNonExistentIDConfig(),
			ExpectError: regexp.MustCompile("Not Found"),
		},
	})
}
