// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0

// Code generated by generators/resource/main.go; DO NOT EDIT.

package vpn_test

import (
	"regexp"
	"testing"

	"github.com/byteplus-sdk/terraform-provider-bytepluscc/internal/acctest"
	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
)

func TestAccByteplusVPNVPNGateway_basic(t *testing.T) {
	td := acctest.NewTestData(t, "Byteplus::VPN::VPNGateway", "bytepluscc_vpn_vpn_gateway", "test")

	td.ResourceTest(t, []resource.TestStep{
		{
			Config:      td.EmptyConfig(),
			ExpectError: regexp.MustCompile("Missing required argument"),
		},
	})
}
