// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0

// Code generated by generators/singular-data-source/main.go; DO NOT EDIT.

package ecs_test

import (
	"regexp"
	"testing"

	"github.com/byteplus/terraform-provider-bytepluscc/internal/acctest"
	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
)

func TestAccVolcengineECSImageDataSource_basic(t *testing.T) {
	td := acctest.NewTestData(t, "Volcengine::ECS::Image", "bytepluscc_ecs_image", "test")

	td.DataSourceTest(t, []resource.TestStep{
		{
			Config:      td.EmptyDataSourceConfig(),
			ExpectError: regexp.MustCompile("Missing required argument"),
		},
	})
}

func TestAccVolcengineECSImageDataSource_NonExistent(t *testing.T) {
	td := acctest.NewTestData(t, "Volcengine::ECS::Image", "bytepluscc_ecs_image", "test")

	td.DataSourceTest(t, []resource.TestStep{
		{
			Config:      td.DataSourceWithNonExistentIDConfig(),
			ExpectError: regexp.MustCompile("Not Found"),
		},
	})
}
