// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0

// Code generated by generators/plural-data-source/main.go; DO NOT EDIT.

package ecs_test

import (
	"fmt"
	"testing"

	"github.com/byteplus/terraform-provider-bytepluscc/internal/acctest"
	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
)

func TestAccVolcengineECSImagesDataSource_basic(t *testing.T) {
	td := acctest.NewTestData(t, "Volcengine::ECS::Image", "bytepluscc_ecs_images", "test")

	td.DataSourceTest(t, []resource.TestStep{
		{
			Config: td.EmptyDataSourceConfig(),
			Check: resource.ComposeTestCheckFunc(
				resource.TestCheckResourceAttrSet(fmt.Sprintf("data.%s", td.ResourceName), "ids.#"),
			),
		},
	})
}
