// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0

// Code generated by generators/singular-data-source/main.go; DO NOT EDIT.

package organization

import (
	"context"

	"github.com/byteplus-sdk/terraform-provider-bytepluscc/internal/generic"
	"github.com/byteplus-sdk/terraform-provider-bytepluscc/internal/registry"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func init() {
	registry.AddDataSourceFactory("bytepluscc_organization_service_control_policy_enabler", serviceControlPolicyEnablerDataSource)
}

// serviceControlPolicyEnablerDataSource returns the Terraform bytepluscc_organization_service_control_policy_enabler data source.
// This Terraform data source corresponds to the Cloud Control Byteplus::Organization::ServiceControlPolicyEnabler resource.
func serviceControlPolicyEnablerDataSource(ctx context.Context) (datasource.DataSource, error) {
	attributes := map[string]schema.Attribute{ /*START SCHEMA*/
		// Property: CanFullAccessDetach
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Can the FullAccess policy be unbound?",
		//	  "type": "boolean"
		//	}
		"can_full_access_detach": schema.BoolAttribute{ /*START ATTRIBUTE*/
			Description: "Can the FullAccess policy be unbound?",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: OrganizationID
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Organization ID",
		//	  "type": "string"
		//	}
		"organization_id": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Organization ID",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: Status
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Activation status, Enabled Disabled PendingEnable PendingDisable",
		//	  "type": "string"
		//	}
		"status": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Activation status, Enabled Disabled PendingEnable PendingDisable",
			Computed:    true,
		}, /*END ATTRIBUTE*/
	} /*END SCHEMA*/

	attributes["id"] = schema.StringAttribute{
		Description: "Uniquely identifies the resource.",
		Required:    true,
	}

	schema := schema.Schema{
		Description: "Data Source schema for Byteplus::Organization::ServiceControlPolicyEnabler",
		Attributes:  attributes,
	}

	var opts generic.DataSourceOptions

	opts = opts.WithCloudControlTypeName("Byteplus::Organization::ServiceControlPolicyEnabler").WithTerraformTypeName("bytepluscc_organization_service_control_policy_enabler")
	opts = opts.WithTerraformSchema(schema)
	opts = opts.WithAttributeNameMap(map[string]string{
		"can_full_access_detach": "CanFullAccessDetach",
		"organization_id":        "OrganizationID",
		"status":                 "Status",
	})

	v, err := generic.NewSingularDataSource(ctx, opts...)

	if err != nil {
		return nil, err
	}

	return v, nil
}
