// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0

// Code generated by generators/resource/main.go; DO NOT EDIT.

package privatelink_test

import (
	"testing"

	"github.com/byteplus-sdk/terraform-provider-bytepluscc/internal/acctest"
	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
)

func TestAccByteplusPrivateLinkEndpointService_basic(t *testing.T) {
	td := acctest.NewTestData(t, "Byteplus::PrivateLink::EndpointService", "bytepluscc_privatelink_endpoint_service", "test")

	td.ResourceTest(t, []resource.TestStep{
		{
			Config: td.EmptyConfig(),
			Check: resource.ComposeTestCheckFunc(
				td.CheckExistsInVolcengine(),
			),
		},
		{
			ResourceName:      td.ResourceName,
			ImportState:       true,
			ImportStateVerify: true,
		},
	})
}

func TestAccByteplusPrivateLinkEndpointService_disappears(t *testing.T) {
	td := acctest.NewTestData(t, "Byteplus::PrivateLink::EndpointService", "bytepluscc_privatelink_endpoint_service", "test")

	td.ResourceTest(t, []resource.TestStep{
		{
			Config: td.EmptyConfig(),
			Check: resource.ComposeTestCheckFunc(
				td.CheckExistsInVolcengine(),
				td.DeleteResource(),
			),
			ExpectNonEmptyPlan: true,
		},
	})
}
