// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0

// Code generated by generators/singular-data-source/main.go; DO NOT EDIT.

package cr

import (
	"context"

	"github.com/byteplus-sdk/terraform-provider-bytepluscc/internal/generic"
	"github.com/byteplus-sdk/terraform-provider-bytepluscc/internal/registry"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func init() {
	registry.AddDataSourceFactory("bytepluscc_cr_endpoint_acl_policy", endpointAclPolicyDataSource)
}

// endpointAclPolicyDataSource returns the Terraform bytepluscc_cr_endpoint_acl_policy data source.
// This Terraform data source corresponds to the Cloud Control Byteplus::CR::EndpointAclPolicy resource.
func endpointAclPolicyDataSource(ctx context.Context) (datasource.DataSource, error) {
	attributes := map[string]schema.Attribute{ /*START SCHEMA*/
		// Property: Description
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Description of the allowlist IPs",
		//	  "type": "string"
		//	}
		"description": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Description of the allowlist IPs",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: Entry
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Allowlist IPs to be added",
		//	  "type": "string"
		//	}
		"entry": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Allowlist IPs to be added",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: Registry
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Name of the image repository instance. On the Instance List page in the Image Repository Console, obtain the instance name",
		//	  "maxLength": 30,
		//	  "minLength": 3,
		//	  "type": "string"
		//	}
		"registry": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Name of the image repository instance. On the Instance List page in the Image Repository Console, obtain the instance name",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: Type
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Network type of the allowlist; currently only Public is supported",
		//	  "type": "string"
		//	}
		"type": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Network type of the allowlist; currently only Public is supported",
			Computed:    true,
		}, /*END ATTRIBUTE*/
	} /*END SCHEMA*/

	attributes["id"] = schema.StringAttribute{
		Description: "Uniquely identifies the resource.",
		Required:    true,
	}

	schema := schema.Schema{
		Description: "Data Source schema for Byteplus::CR::EndpointAclPolicy",
		Attributes:  attributes,
	}

	var opts generic.DataSourceOptions

	opts = opts.WithCloudControlTypeName("Byteplus::CR::EndpointAclPolicy").WithTerraformTypeName("bytepluscc_cr_endpoint_acl_policy")
	opts = opts.WithTerraformSchema(schema)
	opts = opts.WithAttributeNameMap(map[string]string{
		"description": "Description",
		"entry":       "Entry",
		"registry":    "Registry",
		"type":        "Type",
	})

	v, err := generic.NewSingularDataSource(ctx, opts...)

	if err != nil {
		return nil, err
	}

	return v, nil
}
