// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0

// Code generated by generators/singular-data-source/main.go; DO NOT EDIT.

package vke

import (
	"context"

	"github.com/byteplus-sdk/terraform-provider-bytepluscc/internal/generic"
	"github.com/byteplus-sdk/terraform-provider-bytepluscc/internal/registry"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func init() {
	registry.AddDataSourceFactory("bytepluscc_vke_kubeconfig", kubeconfigDataSource)
}

// kubeconfigDataSource returns the Terraform bytepluscc_vke_kubeconfig data source.
// This Terraform data source corresponds to the Cloud Control Byteplus::VKE::Kubeconfig resource.
func kubeconfigDataSource(ctx context.Context) (datasource.DataSource, error) {
	attributes := map[string]schema.Attribute{ /*START SCHEMA*/
		// Property: ClusterId
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Cluster ID",
		//	  "type": "string"
		//	}
		"cluster_id": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Cluster ID",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: CreateTime
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Kubeconfig Creation Time",
		//	  "type": "string"
		//	}
		"create_time": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Kubeconfig Creation Time",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: ExpireTime
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Kubeconfig Expiration Time",
		//	  "type": "string"
		//	}
		"expire_time": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Kubeconfig Expiration Time",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: Kubeconfig
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Kubeconfig Text",
		//	  "type": "string"
		//	}
		"kubeconfig": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Kubeconfig Text",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: KubeconfigId
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "KubeconfigID。",
		//	  "type": "string"
		//	}
		"kubeconfig_id": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "KubeconfigID。",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: RoleId
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Role ID",
		//	  "format": "int64",
		//	  "type": "integer"
		//	}
		"role_id": schema.Int64Attribute{ /*START ATTRIBUTE*/
			Description: "Role ID",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: Type
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Cluster Kubeconfig File Type",
		//	  "type": "string"
		//	}
		"type": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Cluster Kubeconfig File Type",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: UserId
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "User ID",
		//	  "format": "int64",
		//	  "type": "integer"
		//	}
		"user_id": schema.Int64Attribute{ /*START ATTRIBUTE*/
			Description: "User ID",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: ValidDuration
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Kubeconfig File Validity Period",
		//	  "format": "int32",
		//	  "type": "integer"
		//	}
		"valid_duration": schema.Int64Attribute{ /*START ATTRIBUTE*/
			Description: "Kubeconfig File Validity Period",
			Computed:    true,
		}, /*END ATTRIBUTE*/
	} /*END SCHEMA*/

	attributes["id"] = schema.StringAttribute{
		Description: "Uniquely identifies the resource.",
		Required:    true,
	}

	schema := schema.Schema{
		Description: "Data Source schema for Byteplus::VKE::Kubeconfig",
		Attributes:  attributes,
	}

	var opts generic.DataSourceOptions

	opts = opts.WithCloudControlTypeName("Byteplus::VKE::Kubeconfig").WithTerraformTypeName("bytepluscc_vke_kubeconfig")
	opts = opts.WithTerraformSchema(schema)
	opts = opts.WithAttributeNameMap(map[string]string{
		"cluster_id":     "ClusterId",
		"create_time":    "CreateTime",
		"expire_time":    "ExpireTime",
		"kubeconfig":     "Kubeconfig",
		"kubeconfig_id":  "KubeconfigId",
		"role_id":        "RoleId",
		"type":           "Type",
		"user_id":        "UserId",
		"valid_duration": "ValidDuration",
	})

	v, err := generic.NewSingularDataSource(ctx, opts...)

	if err != nil {
		return nil, err
	}

	return v, nil
}
