// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0

// Code generated by generators/singular-data-source/main.go; DO NOT EDIT.

package apig

import (
	"context"

	"github.com/byteplus-sdk/terraform-provider-bytepluscc/internal/generic"
	"github.com/byteplus-sdk/terraform-provider-bytepluscc/internal/registry"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

func init() {
	registry.AddDataSourceFactory("bytepluscc_apig_custom_domain", customDomainDataSource)
}

// customDomainDataSource returns the Terraform bytepluscc_apig_custom_domain data source.
// This Terraform data source corresponds to the Cloud Control Byteplus::APIG::CustomDomain resource.
func customDomainDataSource(ctx context.Context) (datasource.DataSource, error) {
	attributes := map[string]schema.Attribute{ /*START SCHEMA*/
		// Property: CertificateId
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Custom Domain Certificate ID",
		//	  "type": "string"
		//	}
		"certificate_id": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Custom Domain Certificate ID",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: Comments
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Remarks",
		//	  "type": "string"
		//	}
		"comments": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Remarks",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: CreatedTime
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Creation Time",
		//	  "type": "string"
		//	}
		"created_time": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Creation Time",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: CustomDomainId
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Custom Domain ID",
		//	  "type": "string"
		//	}
		"custom_domain_id": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Custom Domain ID",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: Domain
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Custom Domain",
		//	  "type": "string"
		//	}
		"domain": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Custom Domain",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: Protocol
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Protocol. Values: HTTP, HTTPS",
		//	  "insertionOrder": false,
		//	  "items": {
		//	    "type": "string"
		//	  },
		//	  "type": "array",
		//	  "uniqueItems": true
		//	}
		"protocol": schema.SetAttribute{ /*START ATTRIBUTE*/
			ElementType: types.StringType,
			Description: "Protocol. Values: HTTP, HTTPS",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: SSLRedirect
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Redirect to HTTPS",
		//	  "type": "boolean"
		//	}
		"ssl_redirect": schema.BoolAttribute{ /*START ATTRIBUTE*/
			Description: "Redirect to HTTPS",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: ServiceId
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Service ID",
		//	  "type": "string"
		//	}
		"service_id": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Service ID",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: Status
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Status. Values: Creating: configuring; CreationFailed: configuration failed; Deleting: deleting; DeletionFailed: deletion failed; Verified: active",
		//	  "type": "string"
		//	}
		"status": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Status. Values: Creating: configuring; CreationFailed: configuration failed; Deleting: deleting; DeletionFailed: deletion failed; Verified: active",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: UpdatedTime
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Update Time",
		//	  "type": "string"
		//	}
		"updated_time": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Update Time",
			Computed:    true,
		}, /*END ATTRIBUTE*/
	} /*END SCHEMA*/

	attributes["id"] = schema.StringAttribute{
		Description: "Uniquely identifies the resource.",
		Required:    true,
	}

	schema := schema.Schema{
		Description: "Data Source schema for Byteplus::APIG::CustomDomain",
		Attributes:  attributes,
	}

	var opts generic.DataSourceOptions

	opts = opts.WithCloudControlTypeName("Byteplus::APIG::CustomDomain").WithTerraformTypeName("bytepluscc_apig_custom_domain")
	opts = opts.WithTerraformSchema(schema)
	opts = opts.WithAttributeNameMap(map[string]string{
		"certificate_id":   "CertificateId",
		"comments":         "Comments",
		"created_time":     "CreatedTime",
		"custom_domain_id": "CustomDomainId",
		"domain":           "Domain",
		"protocol":         "Protocol",
		"service_id":       "ServiceId",
		"ssl_redirect":     "SSLRedirect",
		"status":           "Status",
		"updated_time":     "UpdatedTime",
	})

	v, err := generic.NewSingularDataSource(ctx, opts...)

	if err != nil {
		return nil, err
	}

	return v, nil
}
