// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0

// Code generated by generators/schema/main.go; DO NOT EDIT.
//go:generate go run generators/plural-data-source/main.go -data-source bytepluscc_ecs_images -cctype Volcengine::ECS::Image -package ecs ../byteplus/ecs/image_plural_data_source_gen.go ../byteplus/ecs/image_plural_data_source_gen_test.go

package provider

import (
	_ "github.com/byteplus/terraform-provider-bytepluscc/internal/byteplus/ecs"
)
