// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0

// Code generated by generators/schema/main.go; DO NOT EDIT.
//go:generate go run generators/plural-data-source/main.go -data-source bytepluscc_ecs_images -cctype Byteplus::ECS::Image -package ecs ../byteplus/ecs/image_plural_data_source_gen.go ../byteplus/ecs/image_plural_data_source_gen_test.go
//go:generate go run generators/plural-data-source/main.go -data-source bytepluscc_clb_listeners -cctype Byteplus::CLB::Listener -package clb ../byteplus/clb/listener_plural_data_source_gen.go ../byteplus/clb/listener_plural_data_source_gen_test.go
//go:generate go run generators/plural-data-source/main.go -data-source bytepluscc_vpc_vpcs -cctype Byteplus::VPC::VPC -package vpc ../byteplus/vpc/vpc_plural_data_source_gen.go ../byteplus/vpc/vpc_plural_data_source_gen_test.go
//go:generate go run generators/plural-data-source/main.go -data-source bytepluscc_storageebs_volumes -cctype Byteplus::StorageEBS::Volume -package storageebs ../byteplus/storageebs/volume_plural_data_source_gen.go ../byteplus/storageebs/volume_plural_data_source_gen_test.go
//go:generate go run generators/plural-data-source/main.go -data-source bytepluscc_alb_listeners -cctype Byteplus::ALB::Listener -package alb ../byteplus/alb/listener_plural_data_source_gen.go ../byteplus/alb/listener_plural_data_source_gen_test.go
//go:generate go run generators/plural-data-source/main.go -data-source bytepluscc_cr_repositories -cctype Byteplus::CR::Repository -package cr ../byteplus/cr/repository_plural_data_source_gen.go ../byteplus/cr/repository_plural_data_source_gen_test.go
//go:generate go run generators/plural-data-source/main.go -data-source bytepluscc_ecs_instances -cctype Byteplus::ECS::Instance -package ecs ../byteplus/ecs/instance_plural_data_source_gen.go ../byteplus/ecs/instance_plural_data_source_gen_test.go
//go:generate go run generators/plural-data-source/main.go -data-source bytepluscc_vke_permissions -cctype Byteplus::VKE::Permission -package vke ../byteplus/vke/permission_plural_data_source_gen.go ../byteplus/vke/permission_plural_data_source_gen_test.go
//go:generate go run generators/plural-data-source/main.go -data-source bytepluscc_vefaas_sandboxes -cctype Byteplus::VEFAAS::Sandbox -package vefaas ../byteplus/vefaas/sandbox_plural_data_source_gen.go ../byteplus/vefaas/sandbox_plural_data_source_gen_test.go
//go:generate go run generators/plural-data-source/main.go -data-source bytepluscc_vefaas_kafka_triggers -cctype Byteplus::VEFAAS::KafkaTrigger -package vefaas ../byteplus/vefaas/kafka_trigger_plural_data_source_gen.go ../byteplus/vefaas/kafka_trigger_plural_data_source_gen_test.go
//go:generate go run generators/plural-data-source/main.go -data-source bytepluscc_cdn_share_configs -cctype Byteplus::CDN::ShareConfig -package cdn ../byteplus/cdn/share_config_plural_data_source_gen.go ../byteplus/cdn/share_config_plural_data_source_gen_test.go
//go:generate go run generators/plural-data-source/main.go -data-source bytepluscc_apig_upstreams -cctype Byteplus::APIG::Upstream -package apig ../byteplus/apig/upstream_plural_data_source_gen.go ../byteplus/apig/upstream_plural_data_source_gen_test.go
//go:generate go run generators/plural-data-source/main.go -data-source bytepluscc_apig_upstream_sources -cctype Byteplus::APIG::UpstreamSource -package apig ../byteplus/apig/upstream_source_plural_data_source_gen.go ../byteplus/apig/upstream_source_plural_data_source_gen_test.go
//go:generate go run generators/plural-data-source/main.go -data-source bytepluscc_apig_gateway_services -cctype Byteplus::APIG::GatewayService -package apig ../byteplus/apig/gateway_service_plural_data_source_gen.go ../byteplus/apig/gateway_service_plural_data_source_gen_test.go
//go:generate go run generators/plural-data-source/main.go -data-source bytepluscc_iam_policies -cctype Byteplus::IAM::Policy -package iam ../byteplus/iam/policy_plural_data_source_gen.go ../byteplus/iam/policy_plural_data_source_gen_test.go
//go:generate go run generators/plural-data-source/main.go -data-source bytepluscc_iam_roles -cctype Byteplus::IAM::Role -package iam ../byteplus/iam/role_plural_data_source_gen.go ../byteplus/iam/role_plural_data_source_gen_test.go
//go:generate go run generators/plural-data-source/main.go -data-source bytepluscc_iam_users -cctype Byteplus::IAM::User -package iam ../byteplus/iam/user_plural_data_source_gen.go ../byteplus/iam/user_plural_data_source_gen_test.go
//go:generate go run generators/plural-data-source/main.go -data-source bytepluscc_natgateway_ngws -cctype Byteplus::NatGateway::NGW -package natgateway ../byteplus/natgateway/ngw_plural_data_source_gen.go ../byteplus/natgateway/ngw_plural_data_source_gen_test.go
//go:generate go run generators/plural-data-source/main.go -data-source bytepluscc_organization_units -cctype Byteplus::Organization::Unit -package organization ../byteplus/organization/unit_plural_data_source_gen.go ../byteplus/organization/unit_plural_data_source_gen_test.go
//go:generate go run generators/plural-data-source/main.go -data-source bytepluscc_rdsmysql_db_accounts -cctype Byteplus::RDSMySQL::DBAccount -package rdsmysql ../byteplus/rdsmysql/db_account_plural_data_source_gen.go ../byteplus/rdsmysql/db_account_plural_data_source_gen_test.go
//go:generate go run generators/plural-data-source/main.go -data-source bytepluscc_autoscaling_scaling_groups -cctype Byteplus::AutoScaling::ScalingGroup -package autoscaling ../byteplus/autoscaling/scaling_group_plural_data_source_gen.go ../byteplus/autoscaling/scaling_group_plural_data_source_gen_test.go
//go:generate go run generators/plural-data-source/main.go -data-source bytepluscc_cen_cens -cctype Byteplus::CEN::CEN -package cen ../byteplus/cen/cen_plural_data_source_gen.go ../byteplus/cen/cen_plural_data_source_gen_test.go
//go:generate go run generators/plural-data-source/main.go -data-source bytepluscc_natgateway_snatentries -cctype Byteplus::NatGateway::Snatentry -package natgateway ../byteplus/natgateway/snatentry_plural_data_source_gen.go ../byteplus/natgateway/snatentry_plural_data_source_gen_test.go
//go:generate go run generators/plural-data-source/main.go -data-source bytepluscc_natgateway_dnatentries -cctype Byteplus::NatGateway::Dnatentry -package natgateway ../byteplus/natgateway/dnatentry_plural_data_source_gen.go ../byteplus/natgateway/dnatentry_plural_data_source_gen_test.go
//go:generate go run generators/plural-data-source/main.go -data-source bytepluscc_natgateway_nat_ips -cctype Byteplus::NatGateway::NatIp -package natgateway ../byteplus/natgateway/nat_ip_plural_data_source_gen.go ../byteplus/natgateway/nat_ip_plural_data_source_gen_test.go
//go:generate go run generators/plural-data-source/main.go -data-source bytepluscc_vke_clusters -cctype Byteplus::VKE::Cluster -package vke ../byteplus/vke/cluster_plural_data_source_gen.go ../byteplus/vke/cluster_plural_data_source_gen_test.go
//go:generate go run generators/plural-data-source/main.go -data-source bytepluscc_rdsmysql_instances -cctype Byteplus::RDSMySQL::Instance -package rdsmysql ../byteplus/rdsmysql/instance_plural_data_source_gen.go ../byteplus/rdsmysql/instance_plural_data_source_gen_test.go
//go:generate go run generators/plural-data-source/main.go -data-source bytepluscc_escloud_instances -cctype Byteplus::ESCloud::Instance -package escloud ../byteplus/escloud/instance_plural_data_source_gen.go ../byteplus/escloud/instance_plural_data_source_gen_test.go
//go:generate go run generators/plural-data-source/main.go -data-source bytepluscc_kms_keys -cctype Byteplus::KMS::Key -package kms ../byteplus/kms/key_plural_data_source_gen.go ../byteplus/kms/key_plural_data_source_gen_test.go
//go:generate go run generators/plural-data-source/main.go -data-source bytepluscc_apig_gateways -cctype Byteplus::APIG::Gateway -package apig ../byteplus/apig/gateway_plural_data_source_gen.go ../byteplus/apig/gateway_plural_data_source_gen_test.go
//go:generate go run generators/plural-data-source/main.go -data-source bytepluscc_apig_custom_domains -cctype Byteplus::APIG::CustomDomain -package apig ../byteplus/apig/custom_domain_plural_data_source_gen.go ../byteplus/apig/custom_domain_plural_data_source_gen_test.go
//go:generate go run generators/plural-data-source/main.go -data-source bytepluscc_hbase_instances -cctype Byteplus::HBase::Instance -package hbase ../byteplus/hbase/instance_plural_data_source_gen.go ../byteplus/hbase/instance_plural_data_source_gen_test.go
//go:generate go run generators/plural-data-source/main.go -data-source bytepluscc_alb_certificates -cctype Byteplus::ALB::Certificate -package alb ../byteplus/alb/certificate_plural_data_source_gen.go ../byteplus/alb/certificate_plural_data_source_gen_test.go
//go:generate go run generators/plural-data-source/main.go -data-source bytepluscc_vke_addons -cctype Byteplus::VKE::Addon -package vke ../byteplus/vke/addon_plural_data_source_gen.go ../byteplus/vke/addon_plural_data_source_gen_test.go
//go:generate go run generators/plural-data-source/main.go -data-source bytepluscc_vke_node_pools -cctype Byteplus::VKE::NodePool -package vke ../byteplus/vke/node_pool_plural_data_source_gen.go ../byteplus/vke/node_pool_plural_data_source_gen_test.go
//go:generate go run generators/plural-data-source/main.go -data-source bytepluscc_vpc_security_groups -cctype Byteplus::VPC::SecurityGroup -package vpc ../byteplus/vpc/security_group_plural_data_source_gen.go ../byteplus/vpc/security_group_plural_data_source_gen_test.go
//go:generate go run generators/plural-data-source/main.go -data-source bytepluscc_vpc_enis -cctype Byteplus::VPC::ENI -package vpc ../byteplus/vpc/eni_plural_data_source_gen.go ../byteplus/vpc/eni_plural_data_source_gen_test.go
//go:generate go run generators/plural-data-source/main.go -data-source bytepluscc_redis_instances -cctype Byteplus::Redis::Instance -package redis ../byteplus/redis/instance_plural_data_source_gen.go ../byteplus/redis/instance_plural_data_source_gen_test.go
//go:generate go run generators/plural-data-source/main.go -data-source bytepluscc_vepfs_instances -cctype Byteplus::VEPFS::Instance -package vepfs ../byteplus/vepfs/instance_plural_data_source_gen.go ../byteplus/vepfs/instance_plural_data_source_gen_test.go
//go:generate go run generators/plural-data-source/main.go -data-source bytepluscc_storageebs_snapshots -cctype Byteplus::StorageEBS::Snapshot -package storageebs ../byteplus/storageebs/snapshot_plural_data_source_gen.go ../byteplus/storageebs/snapshot_plural_data_source_gen_test.go
//go:generate go run generators/plural-data-source/main.go -data-source bytepluscc_kafka_topics -cctype Byteplus::Kafka::Topic -package kafka ../byteplus/kafka/topic_plural_data_source_gen.go ../byteplus/kafka/topic_plural_data_source_gen_test.go
//go:generate go run generators/plural-data-source/main.go -data-source bytepluscc_dns_zones -cctype Byteplus::DNS::Zone -package dns ../byteplus/dns/zone_plural_data_source_gen.go ../byteplus/dns/zone_plural_data_source_gen_test.go
//go:generate go run generators/plural-data-source/main.go -data-source bytepluscc_iam_projects -cctype Byteplus::IAM::Project -package iam ../byteplus/iam/project_plural_data_source_gen.go ../byteplus/iam/project_plural_data_source_gen_test.go
//go:generate go run generators/plural-data-source/main.go -data-source bytepluscc_cloudidentity_users -cctype Byteplus::CloudIdentity::User -package cloudidentity ../byteplus/cloudidentity/user_plural_data_source_gen.go ../byteplus/cloudidentity/user_plural_data_source_gen_test.go
//go:generate go run generators/plural-data-source/main.go -data-source bytepluscc_bmq_instances -cctype Byteplus::BMQ::Instance -package bmq ../byteplus/bmq/instance_plural_data_source_gen.go ../byteplus/bmq/instance_plural_data_source_gen_test.go
//go:generate go run generators/plural-data-source/main.go -data-source bytepluscc_privatelink_endpoint_services -cctype Byteplus::PrivateLink::EndpointService -package privatelink ../byteplus/privatelink/endpoint_service_plural_data_source_gen.go ../byteplus/privatelink/endpoint_service_plural_data_source_gen_test.go
//go:generate go run generators/plural-data-source/main.go -data-source bytepluscc_fwcenter_dns_control_policies -cctype Byteplus::FWCenter::DnsControlPolicy -package fwcenter ../byteplus/fwcenter/dns_control_policy_plural_data_source_gen.go ../byteplus/fwcenter/dns_control_policy_plural_data_source_gen_test.go
//go:generate go run generators/plural-data-source/main.go -data-source bytepluscc_clb_rules -cctype Byteplus::CLB::Rule -package clb ../byteplus/clb/rule_plural_data_source_gen.go ../byteplus/clb/rule_plural_data_source_gen_test.go
//go:generate go run generators/plural-data-source/main.go -data-source bytepluscc_vpc_subnets -cctype Byteplus::VPC::Subnet -package vpc ../byteplus/vpc/subnet_plural_data_source_gen.go ../byteplus/vpc/subnet_plural_data_source_gen_test.go
//go:generate go run generators/plural-data-source/main.go -data-source bytepluscc_bmq_groups -cctype Byteplus::BMQ::Group -package bmq ../byteplus/bmq/group_plural_data_source_gen.go ../byteplus/bmq/group_plural_data_source_gen_test.go
//go:generate go run generators/plural-data-source/main.go -data-source bytepluscc_cloudmonitor_rules -cctype Byteplus::CloudMonitor::Rule -package cloudmonitor ../byteplus/cloudmonitor/rule_plural_data_source_gen.go ../byteplus/cloudmonitor/rule_plural_data_source_gen_test.go
//go:generate go run generators/plural-data-source/main.go -data-source bytepluscc_clb_nlb_server_groups -cctype Byteplus::CLB::NLBServerGroup -package clb ../byteplus/clb/nlb_server_group_plural_data_source_gen.go ../byteplus/clb/nlb_server_group_plural_data_source_gen_test.go
//go:generate go run generators/plural-data-source/main.go -data-source bytepluscc_clb_nlb_listeners -cctype Byteplus::CLB::NLBListener -package clb ../byteplus/clb/nlb_listener_plural_data_source_gen.go ../byteplus/clb/nlb_listener_plural_data_source_gen_test.go
//go:generate go run generators/plural-data-source/main.go -data-source bytepluscc_clb_server_groups -cctype Byteplus::CLB::ServerGroup -package clb ../byteplus/clb/server_group_plural_data_source_gen.go ../byteplus/clb/server_group_plural_data_source_gen_test.go
//go:generate go run generators/plural-data-source/main.go -data-source bytepluscc_directconnect_direct_connect_gateways -cctype Byteplus::DirectConnect::DirectConnectGateway -package directconnect ../byteplus/directconnect/direct_connect_gateway_plural_data_source_gen.go ../byteplus/directconnect/direct_connect_gateway_plural_data_source_gen_test.go
//go:generate go run generators/plural-data-source/main.go -data-source bytepluscc_vpc_eips -cctype Byteplus::VPC::EIP -package vpc ../byteplus/vpc/eip_plural_data_source_gen.go ../byteplus/vpc/eip_plural_data_source_gen_test.go
//go:generate go run generators/plural-data-source/main.go -data-source bytepluscc_vpc_route_tables -cctype Byteplus::VPC::RouteTable -package vpc ../byteplus/vpc/route_table_plural_data_source_gen.go ../byteplus/vpc/route_table_plural_data_source_gen_test.go
//go:generate go run generators/plural-data-source/main.go -data-source bytepluscc_filenas_instances -cctype Byteplus::FileNAS::Instance -package filenas ../byteplus/filenas/instance_plural_data_source_gen.go ../byteplus/filenas/instance_plural_data_source_gen_test.go
//go:generate go run generators/plural-data-source/main.go -data-source bytepluscc_ecs_keypairs -cctype Byteplus::ECS::Keypair -package ecs ../byteplus/ecs/keypair_plural_data_source_gen.go ../byteplus/ecs/keypair_plural_data_source_gen_test.go
//go:generate go run generators/plural-data-source/main.go -data-source bytepluscc_ecs_invocations -cctype Byteplus::ECS::Invocation -package ecs ../byteplus/ecs/invocation_plural_data_source_gen.go ../byteplus/ecs/invocation_plural_data_source_gen_test.go
//go:generate go run generators/plural-data-source/main.go -data-source bytepluscc_cr_name_spaces -cctype Byteplus::CR::NameSpace -package cr ../byteplus/cr/name_space_plural_data_source_gen.go ../byteplus/cr/name_space_plural_data_source_gen_test.go
//go:generate go run generators/plural-data-source/main.go -data-source bytepluscc_cr_registries -cctype Byteplus::CR::Registry -package cr ../byteplus/cr/registry_plural_data_source_gen.go ../byteplus/cr/registry_plural_data_source_gen_test.go
//go:generate go run generators/plural-data-source/main.go -data-source bytepluscc_vpc_bandwidth_packages -cctype Byteplus::VPC::BandwidthPackage -package vpc ../byteplus/vpc/bandwidth_package_plural_data_source_gen.go ../byteplus/vpc/bandwidth_package_plural_data_source_gen_test.go
//go:generate go run generators/plural-data-source/main.go -data-source bytepluscc_transitrouter_transit_router_route_tables -cctype Byteplus::TransitRouter::TransitRouterRouteTable -package transitrouter ../byteplus/transitrouter/transit_router_route_table_plural_data_source_gen.go ../byteplus/transitrouter/transit_router_route_table_plural_data_source_gen_test.go
//go:generate go run generators/plural-data-source/main.go -data-source bytepluscc_transitrouter_transit_router_route_entries -cctype Byteplus::TransitRouter::TransitRouterRouteEntry -package transitrouter ../byteplus/transitrouter/transit_router_route_entry_plural_data_source_gen.go ../byteplus/transitrouter/transit_router_route_entry_plural_data_source_gen_test.go
//go:generate go run generators/plural-data-source/main.go -data-source bytepluscc_alb_acls -cctype Byteplus::ALB::ACL -package alb ../byteplus/alb/acl_plural_data_source_gen.go ../byteplus/alb/acl_plural_data_source_gen_test.go
//go:generate go run generators/plural-data-source/main.go -data-source bytepluscc_alb_server_groups -cctype Byteplus::ALB::ServerGroup -package alb ../byteplus/alb/server_group_plural_data_source_gen.go ../byteplus/alb/server_group_plural_data_source_gen_test.go
//go:generate go run generators/plural-data-source/main.go -data-source bytepluscc_alb_load_balancers -cctype Byteplus::ALB::LoadBalancer -package alb ../byteplus/alb/load_balancer_plural_data_source_gen.go ../byteplus/alb/load_balancer_plural_data_source_gen_test.go
//go:generate go run generators/plural-data-source/main.go -data-source bytepluscc_autoscaling_scaling_configurations -cctype Byteplus::AutoScaling::ScalingConfiguration -package autoscaling ../byteplus/autoscaling/scaling_configuration_plural_data_source_gen.go ../byteplus/autoscaling/scaling_configuration_plural_data_source_gen_test.go
//go:generate go run generators/plural-data-source/main.go -data-source bytepluscc_iam_groups -cctype Byteplus::IAM::Group -package iam ../byteplus/iam/group_plural_data_source_gen.go ../byteplus/iam/group_plural_data_source_gen_test.go
//go:generate go run generators/plural-data-source/main.go -data-source bytepluscc_vpc_network_acls -cctype Byteplus::VPC::NetworkAcl -package vpc ../byteplus/vpc/network_acl_plural_data_source_gen.go ../byteplus/vpc/network_acl_plural_data_source_gen_test.go
//go:generate go run generators/plural-data-source/main.go -data-source bytepluscc_transitrouter_transit_routers -cctype Byteplus::TransitRouter::TransitRouter -package transitrouter ../byteplus/transitrouter/transit_router_plural_data_source_gen.go ../byteplus/transitrouter/transit_router_plural_data_source_gen_test.go
//go:generate go run generators/plural-data-source/main.go -data-source bytepluscc_vmp_workspaces -cctype Byteplus::VMP::Workspace -package vmp ../byteplus/vmp/workspace_plural_data_source_gen.go ../byteplus/vmp/workspace_plural_data_source_gen_test.go
//go:generate go run generators/plural-data-source/main.go -data-source bytepluscc_vpn_vpn_gateways -cctype Byteplus::VPN::VPNGateway -package vpn ../byteplus/vpn/vpn_gateway_plural_data_source_gen.go ../byteplus/vpn/vpn_gateway_plural_data_source_gen_test.go
//go:generate go run generators/plural-data-source/main.go -data-source bytepluscc_clb_nlbs -cctype Byteplus::CLB::NLB -package clb ../byteplus/clb/nlb_plural_data_source_gen.go ../byteplus/clb/nlb_plural_data_source_gen_test.go
//go:generate go run generators/plural-data-source/main.go -data-source bytepluscc_filenas_snapshots -cctype Byteplus::FileNAS::Snapshot -package filenas ../byteplus/filenas/snapshot_plural_data_source_gen.go ../byteplus/filenas/snapshot_plural_data_source_gen_test.go
//go:generate go run generators/plural-data-source/main.go -data-source bytepluscc_ecs_commands -cctype Byteplus::ECS::Command -package ecs ../byteplus/ecs/command_plural_data_source_gen.go ../byteplus/ecs/command_plural_data_source_gen_test.go
//go:generate go run generators/plural-data-source/main.go -data-source bytepluscc_clb_acls -cctype Byteplus::CLB::ACL -package clb ../byteplus/clb/acl_plural_data_source_gen.go ../byteplus/clb/acl_plural_data_source_gen_test.go
//go:generate go run generators/plural-data-source/main.go -data-source bytepluscc_clb_certificates -cctype Byteplus::CLB::Certificate -package clb ../byteplus/clb/certificate_plural_data_source_gen.go ../byteplus/clb/certificate_plural_data_source_gen_test.go
//go:generate go run generators/plural-data-source/main.go -data-source bytepluscc_vpc_prefix_lists -cctype Byteplus::VPC::PrefixList -package vpc ../byteplus/vpc/prefix_list_plural_data_source_gen.go ../byteplus/vpc/prefix_list_plural_data_source_gen_test.go
//go:generate go run generators/plural-data-source/main.go -data-source bytepluscc_rdsmysql_databases -cctype Byteplus::RDSMySQL::Database -package rdsmysql ../byteplus/rdsmysql/database_plural_data_source_gen.go ../byteplus/rdsmysql/database_plural_data_source_gen_test.go

package provider

import (
	_ "github.com/byteplus-sdk/terraform-provider-bytepluscc/internal/byteplus/alb"
	_ "github.com/byteplus-sdk/terraform-provider-bytepluscc/internal/byteplus/apig"
	_ "github.com/byteplus-sdk/terraform-provider-bytepluscc/internal/byteplus/autoscaling"
	_ "github.com/byteplus-sdk/terraform-provider-bytepluscc/internal/byteplus/bmq"
	_ "github.com/byteplus-sdk/terraform-provider-bytepluscc/internal/byteplus/cdn"
	_ "github.com/byteplus-sdk/terraform-provider-bytepluscc/internal/byteplus/cen"
	_ "github.com/byteplus-sdk/terraform-provider-bytepluscc/internal/byteplus/clb"
	_ "github.com/byteplus-sdk/terraform-provider-bytepluscc/internal/byteplus/cloudidentity"
	_ "github.com/byteplus-sdk/terraform-provider-bytepluscc/internal/byteplus/cloudmonitor"
	_ "github.com/byteplus-sdk/terraform-provider-bytepluscc/internal/byteplus/cr"
	_ "github.com/byteplus-sdk/terraform-provider-bytepluscc/internal/byteplus/directconnect"
	_ "github.com/byteplus-sdk/terraform-provider-bytepluscc/internal/byteplus/dns"
	_ "github.com/byteplus-sdk/terraform-provider-bytepluscc/internal/byteplus/ecs"
	_ "github.com/byteplus-sdk/terraform-provider-bytepluscc/internal/byteplus/escloud"
	_ "github.com/byteplus-sdk/terraform-provider-bytepluscc/internal/byteplus/filenas"
	_ "github.com/byteplus-sdk/terraform-provider-bytepluscc/internal/byteplus/fwcenter"
	_ "github.com/byteplus-sdk/terraform-provider-bytepluscc/internal/byteplus/hbase"
	_ "github.com/byteplus-sdk/terraform-provider-bytepluscc/internal/byteplus/iam"
	_ "github.com/byteplus-sdk/terraform-provider-bytepluscc/internal/byteplus/kafka"
	_ "github.com/byteplus-sdk/terraform-provider-bytepluscc/internal/byteplus/kms"
	_ "github.com/byteplus-sdk/terraform-provider-bytepluscc/internal/byteplus/natgateway"
	_ "github.com/byteplus-sdk/terraform-provider-bytepluscc/internal/byteplus/organization"
	_ "github.com/byteplus-sdk/terraform-provider-bytepluscc/internal/byteplus/privatelink"
	_ "github.com/byteplus-sdk/terraform-provider-bytepluscc/internal/byteplus/rdsmysql"
	_ "github.com/byteplus-sdk/terraform-provider-bytepluscc/internal/byteplus/redis"
	_ "github.com/byteplus-sdk/terraform-provider-bytepluscc/internal/byteplus/storageebs"
	_ "github.com/byteplus-sdk/terraform-provider-bytepluscc/internal/byteplus/transitrouter"
	_ "github.com/byteplus-sdk/terraform-provider-bytepluscc/internal/byteplus/vefaas"
	_ "github.com/byteplus-sdk/terraform-provider-bytepluscc/internal/byteplus/vepfs"
	_ "github.com/byteplus-sdk/terraform-provider-bytepluscc/internal/byteplus/vke"
	_ "github.com/byteplus-sdk/terraform-provider-bytepluscc/internal/byteplus/vmp"
	_ "github.com/byteplus-sdk/terraform-provider-bytepluscc/internal/byteplus/vpc"
	_ "github.com/byteplus-sdk/terraform-provider-bytepluscc/internal/byteplus/vpn"
)
