// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0

// Code generated by generators/schema/main.go; DO NOT EDIT.
//go:generate go run generators/plural-data-source/main.go -data-source bytepluscc_ecs_images -cctype Byteplus::ECS::Image -package ecs ../byteplus/ecs/image_plural_data_source_gen.go ../byteplus/ecs/image_plural_data_source_gen_test.go
//go:generate go run generators/plural-data-source/main.go -data-source bytepluscc_clb_listeners -cctype Byteplus::CLB::Listener -package clb ../byteplus/clb/listener_plural_data_source_gen.go ../byteplus/clb/listener_plural_data_source_gen_test.go
//go:generate go run generators/plural-data-source/main.go -data-source bytepluscc_vpc_vpcs -cctype Byteplus::VPC::VPC -package vpc ../byteplus/vpc/vpc_plural_data_source_gen.go ../byteplus/vpc/vpc_plural_data_source_gen_test.go
//go:generate go run generators/plural-data-source/main.go -data-source bytepluscc_storageebs_volumes -cctype Byteplus::StorageEBS::Volume -package storageebs ../byteplus/storageebs/volume_plural_data_source_gen.go ../byteplus/storageebs/volume_plural_data_source_gen_test.go
//go:generate go run generators/plural-data-source/main.go -data-source bytepluscc_alb_listeners -cctype Byteplus::ALB::Listener -package alb ../byteplus/alb/listener_plural_data_source_gen.go ../byteplus/alb/listener_plural_data_source_gen_test.go
//go:generate go run generators/plural-data-source/main.go -data-source bytepluscc_cr_repositories -cctype Byteplus::CR::Repository -package cr ../byteplus/cr/repository_plural_data_source_gen.go ../byteplus/cr/repository_plural_data_source_gen_test.go
//go:generate go run generators/plural-data-source/main.go -data-source bytepluscc_autoscaling_scaling_configurations -cctype Byteplus::AutoScaling::ScalingConfiguration -package autoscaling ../byteplus/autoscaling/scaling_configuration_plural_data_source_gen.go ../byteplus/autoscaling/scaling_configuration_plural_data_source_gen_test.go
//go:generate go run generators/plural-data-source/main.go -data-source bytepluscc_ecs_instances -cctype Byteplus::ECS::Instance -package ecs ../byteplus/ecs/instance_plural_data_source_gen.go ../byteplus/ecs/instance_plural_data_source_gen_test.go
//go:generate go run generators/plural-data-source/main.go -data-source bytepluscc_vke_permissions -cctype Byteplus::VKE::Permission -package vke ../byteplus/vke/permission_plural_data_source_gen.go ../byteplus/vke/permission_plural_data_source_gen_test.go
//go:generate go run generators/plural-data-source/main.go -data-source bytepluscc_vefaas_sandboxes -cctype Byteplus::VEFAAS::Sandbox -package vefaas ../byteplus/vefaas/sandbox_plural_data_source_gen.go ../byteplus/vefaas/sandbox_plural_data_source_gen_test.go
//go:generate go run generators/plural-data-source/main.go -data-source bytepluscc_vefaas_kafka_triggers -cctype Byteplus::VEFAAS::KafkaTrigger -package vefaas ../byteplus/vefaas/kafka_trigger_plural_data_source_gen.go ../byteplus/vefaas/kafka_trigger_plural_data_source_gen_test.go
//go:generate go run generators/plural-data-source/main.go -data-source bytepluscc_cdn_share_configs -cctype Byteplus::CDN::ShareConfig -package cdn ../byteplus/cdn/share_config_plural_data_source_gen.go ../byteplus/cdn/share_config_plural_data_source_gen_test.go
//go:generate go run generators/plural-data-source/main.go -data-source bytepluscc_apig_upstreams -cctype Byteplus::APIG::Upstream -package apig ../byteplus/apig/upstream_plural_data_source_gen.go ../byteplus/apig/upstream_plural_data_source_gen_test.go
//go:generate go run generators/plural-data-source/main.go -data-source bytepluscc_apig_upstream_sources -cctype Byteplus::APIG::UpstreamSource -package apig ../byteplus/apig/upstream_source_plural_data_source_gen.go ../byteplus/apig/upstream_source_plural_data_source_gen_test.go
//go:generate go run generators/plural-data-source/main.go -data-source bytepluscc_apig_gateway_services -cctype Byteplus::APIG::GatewayService -package apig ../byteplus/apig/gateway_service_plural_data_source_gen.go ../byteplus/apig/gateway_service_plural_data_source_gen_test.go
//go:generate go run generators/plural-data-source/main.go -data-source bytepluscc_iam_policies -cctype Byteplus::IAM::Policy -package iam ../byteplus/iam/policy_plural_data_source_gen.go ../byteplus/iam/policy_plural_data_source_gen_test.go
//go:generate go run generators/plural-data-source/main.go -data-source bytepluscc_iam_roles -cctype Byteplus::IAM::Role -package iam ../byteplus/iam/role_plural_data_source_gen.go ../byteplus/iam/role_plural_data_source_gen_test.go
//go:generate go run generators/plural-data-source/main.go -data-source bytepluscc_iam_users -cctype Byteplus::IAM::User -package iam ../byteplus/iam/user_plural_data_source_gen.go ../byteplus/iam/user_plural_data_source_gen_test.go
//go:generate go run generators/plural-data-source/main.go -data-source bytepluscc_clb_listeners -cctype Byteplus::CLB::Listener -package clb ../byteplus/clb/listener_plural_data_source_gen.go ../byteplus/clb/listener_plural_data_source_gen_test.go
//go:generate go run generators/plural-data-source/main.go -data-source bytepluscc_natgateway_ngws -cctype Byteplus::NatGateway::NGW -package natgateway ../byteplus/natgateway/ngw_plural_data_source_gen.go ../byteplus/natgateway/ngw_plural_data_source_gen_test.go
//go:generate go run generators/plural-data-source/main.go -data-source bytepluscc_organization_units -cctype Byteplus::Organization::Unit -package organization ../byteplus/organization/unit_plural_data_source_gen.go ../byteplus/organization/unit_plural_data_source_gen_test.go
//go:generate go run generators/plural-data-source/main.go -data-source bytepluscc_rdsmysql_db_accounts -cctype Byteplus::RDSMySQL::DBAccount -package rdsmysql ../byteplus/rdsmysql/db_account_plural_data_source_gen.go ../byteplus/rdsmysql/db_account_plural_data_source_gen_test.go

package provider

import (
	_ "github.com/byteplus-sdk/terraform-provider-bytepluscc/internal/byteplus/alb"
	_ "github.com/byteplus-sdk/terraform-provider-bytepluscc/internal/byteplus/apig"
	_ "github.com/byteplus-sdk/terraform-provider-bytepluscc/internal/byteplus/autoscaling"
	_ "github.com/byteplus-sdk/terraform-provider-bytepluscc/internal/byteplus/cdn"
	_ "github.com/byteplus-sdk/terraform-provider-bytepluscc/internal/byteplus/clb"
	_ "github.com/byteplus-sdk/terraform-provider-bytepluscc/internal/byteplus/cr"
	_ "github.com/byteplus-sdk/terraform-provider-bytepluscc/internal/byteplus/ecs"
	_ "github.com/byteplus-sdk/terraform-provider-bytepluscc/internal/byteplus/iam"
	_ "github.com/byteplus-sdk/terraform-provider-bytepluscc/internal/byteplus/natgateway"
	_ "github.com/byteplus-sdk/terraform-provider-bytepluscc/internal/byteplus/organization"
	_ "github.com/byteplus-sdk/terraform-provider-bytepluscc/internal/byteplus/rdsmysql"
	_ "github.com/byteplus-sdk/terraform-provider-bytepluscc/internal/byteplus/storageebs"
	_ "github.com/byteplus-sdk/terraform-provider-bytepluscc/internal/byteplus/vefaas"
	_ "github.com/byteplus-sdk/terraform-provider-bytepluscc/internal/byteplus/vke"
	_ "github.com/byteplus-sdk/terraform-provider-bytepluscc/internal/byteplus/vpc"
)
