// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0

// Code generated by generators/schema/main.go; DO NOT EDIT.
//go:generate go run generators/resource/main.go -resource bytepluscc_ecs_image -ccschema ../service/cloudcontrol/schemas/Byteplus_ECS_Image.json -package ecs -- ../byteplus/ecs/image_resource_gen.go ../byteplus/ecs/image_resource_gen_test.go
//go:generate go run generators/resource/main.go -resource bytepluscc_clb_listener -ccschema ../service/cloudcontrol/schemas/Byteplus_CLB_Listener.json -package clb -- ../byteplus/clb/listener_resource_gen.go ../byteplus/clb/listener_resource_gen_test.go
//go:generate go run generators/resource/main.go -resource bytepluscc_vpc_vpc -ccschema ../service/cloudcontrol/schemas/Byteplus_VPC_VPC.json -package vpc -- ../byteplus/vpc/vpc_resource_gen.go ../byteplus/vpc/vpc_resource_gen_test.go

package provider

import (
	_ "github.com/byteplus-sdk/terraform-provider-bytepluscc/internal/byteplus/clb"
	_ "github.com/byteplus-sdk/terraform-provider-bytepluscc/internal/byteplus/ecs"
	_ "github.com/byteplus-sdk/terraform-provider-bytepluscc/internal/byteplus/vpc"
)
