// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0

// Code generated by generators/schema/main.go; DO NOT EDIT.
//go:generate go run generators/resource/main.go -resource bytepluscc_ecs_image -ccschema ../service/cloudcontrol/schemas/Byteplus_ECS_Image.json -package ecs -- ../byteplus/ecs/image_resource_gen.go ../byteplus/ecs/image_resource_gen_test.go
//go:generate go run generators/resource/main.go -resource bytepluscc_clb_listener -ccschema ../service/cloudcontrol/schemas/Byteplus_CLB_Listener.json -package clb -- ../byteplus/clb/listener_resource_gen.go ../byteplus/clb/listener_resource_gen_test.go
//go:generate go run generators/resource/main.go -resource bytepluscc_vpc_vpc -ccschema ../service/cloudcontrol/schemas/Byteplus_VPC_VPC.json -package vpc -- ../byteplus/vpc/vpc_resource_gen.go ../byteplus/vpc/vpc_resource_gen_test.go
//go:generate go run generators/resource/main.go -resource bytepluscc_storageebs_volume -ccschema ../service/cloudcontrol/schemas/Byteplus_StorageEBS_Volume.json -package storageebs -- ../byteplus/storageebs/volume_resource_gen.go ../byteplus/storageebs/volume_resource_gen_test.go
//go:generate go run generators/resource/main.go -resource bytepluscc_alb_listener -ccschema ../service/cloudcontrol/schemas/Byteplus_ALB_Listener.json -package alb -- ../byteplus/alb/listener_resource_gen.go ../byteplus/alb/listener_resource_gen_test.go
//go:generate go run generators/resource/main.go -resource bytepluscc_cr_repository -ccschema ../service/cloudcontrol/schemas/Byteplus_CR_Repository.json -package cr -- ../byteplus/cr/repository_resource_gen.go ../byteplus/cr/repository_resource_gen_test.go
//go:generate go run generators/resource/main.go -resource bytepluscc_autoscaling_scaling_configuration -ccschema ../service/cloudcontrol/schemas/Byteplus_AutoScaling_ScalingConfiguration.json -package autoscaling -- ../byteplus/autoscaling/scaling_configuration_resource_gen.go ../byteplus/autoscaling/scaling_configuration_resource_gen_test.go
//go:generate go run generators/resource/main.go -resource bytepluscc_ecs_instance -ccschema ../service/cloudcontrol/schemas/Byteplus_ECS_Instance.json -package ecs -- ../byteplus/ecs/instance_resource_gen.go ../byteplus/ecs/instance_resource_gen_test.go
//go:generate go run generators/resource/main.go -resource bytepluscc_vke_permission -ccschema ../service/cloudcontrol/schemas/Byteplus_VKE_Permission.json -package vke -- ../byteplus/vke/permission_resource_gen.go ../byteplus/vke/permission_resource_gen_test.go
//go:generate go run generators/resource/main.go -resource bytepluscc_vefaas_sandbox -ccschema ../service/cloudcontrol/schemas/Byteplus_VEFAAS_Sandbox.json -package vefaas -- ../byteplus/vefaas/sandbox_resource_gen.go ../byteplus/vefaas/sandbox_resource_gen_test.go
//go:generate go run generators/resource/main.go -resource bytepluscc_vefaas_kafka_trigger -ccschema ../service/cloudcontrol/schemas/Byteplus_VEFAAS_KafkaTrigger.json -package vefaas -- ../byteplus/vefaas/kafka_trigger_resource_gen.go ../byteplus/vefaas/kafka_trigger_resource_gen_test.go
//go:generate go run generators/resource/main.go -resource bytepluscc_cdn_share_config -ccschema ../service/cloudcontrol/schemas/Byteplus_CDN_ShareConfig.json -package cdn -- ../byteplus/cdn/share_config_resource_gen.go ../byteplus/cdn/share_config_resource_gen_test.go
//go:generate go run generators/resource/main.go -resource bytepluscc_apig_upstream -ccschema ../service/cloudcontrol/schemas/Byteplus_APIG_Upstream.json -package apig -- ../byteplus/apig/upstream_resource_gen.go ../byteplus/apig/upstream_resource_gen_test.go
//go:generate go run generators/resource/main.go -resource bytepluscc_apig_upstream_source -ccschema ../service/cloudcontrol/schemas/Byteplus_APIG_UpstreamSource.json -package apig -- ../byteplus/apig/upstream_source_resource_gen.go ../byteplus/apig/upstream_source_resource_gen_test.go
//go:generate go run generators/resource/main.go -resource bytepluscc_apig_gateway_service -ccschema ../service/cloudcontrol/schemas/Byteplus_APIG_GatewayService.json -package apig -- ../byteplus/apig/gateway_service_resource_gen.go ../byteplus/apig/gateway_service_resource_gen_test.go
//go:generate go run generators/resource/main.go -resource bytepluscc_iam_policy -ccschema ../service/cloudcontrol/schemas/Byteplus_IAM_Policy.json -package iam -- ../byteplus/iam/policy_resource_gen.go ../byteplus/iam/policy_resource_gen_test.go
//go:generate go run generators/resource/main.go -resource bytepluscc_iam_role -ccschema ../service/cloudcontrol/schemas/Byteplus_IAM_Role.json -package iam -- ../byteplus/iam/role_resource_gen.go ../byteplus/iam/role_resource_gen_test.go
//go:generate go run generators/resource/main.go -resource bytepluscc_iam_user -ccschema ../service/cloudcontrol/schemas/Byteplus_IAM_User.json -package iam -- ../byteplus/iam/user_resource_gen.go ../byteplus/iam/user_resource_gen_test.go
//go:generate go run generators/resource/main.go -resource bytepluscc_clb_listener -ccschema ../service/cloudcontrol/schemas/Byteplus_CLB_Listener.json -package clb -- ../byteplus/clb/listener_resource_gen.go ../byteplus/clb/listener_resource_gen_test.go
//go:generate go run generators/resource/main.go -resource bytepluscc_natgateway_ngw -ccschema ../service/cloudcontrol/schemas/Byteplus_NatGateway_NGW.json -package natgateway -- ../byteplus/natgateway/ngw_resource_gen.go ../byteplus/natgateway/ngw_resource_gen_test.go
//go:generate go run generators/resource/main.go -resource bytepluscc_organization_unit -ccschema ../service/cloudcontrol/schemas/Byteplus_Organization_Unit.json -package organization -- ../byteplus/organization/unit_resource_gen.go ../byteplus/organization/unit_resource_gen_test.go
//go:generate go run generators/resource/main.go -resource bytepluscc_rdsmysql_db_account -ccschema ../service/cloudcontrol/schemas/Byteplus_RDSMySQL_DBAccount.json -package rdsmysql -- ../byteplus/rdsmysql/db_account_resource_gen.go ../byteplus/rdsmysql/db_account_resource_gen_test.go
//go:generate go run generators/resource/main.go -resource bytepluscc_autoscaling_scaling_group -ccschema ../service/cloudcontrol/schemas/Byteplus_AutoScaling_ScalingGroup.json -package autoscaling -- ../byteplus/autoscaling/scaling_group_resource_gen.go ../byteplus/autoscaling/scaling_group_resource_gen_test.go
//go:generate go run generators/resource/main.go -resource bytepluscc_cen_cen -ccschema ../service/cloudcontrol/schemas/Byteplus_CEN_CEN.json -package cen -- ../byteplus/cen/cen_resource_gen.go ../byteplus/cen/cen_resource_gen_test.go
//go:generate go run generators/resource/main.go -resource bytepluscc_natgateway_snatentry -ccschema ../service/cloudcontrol/schemas/Byteplus_NatGateway_Snatentry.json -package natgateway -- ../byteplus/natgateway/snatentry_resource_gen.go ../byteplus/natgateway/snatentry_resource_gen_test.go
//go:generate go run generators/resource/main.go -resource bytepluscc_natgateway_dnatentry -ccschema ../service/cloudcontrol/schemas/Byteplus_NatGateway_Dnatentry.json -package natgateway -- ../byteplus/natgateway/dnatentry_resource_gen.go ../byteplus/natgateway/dnatentry_resource_gen_test.go
//go:generate go run generators/resource/main.go -resource bytepluscc_natgateway_nat_ip -ccschema ../service/cloudcontrol/schemas/Byteplus_NatGateway_NatIp.json -package natgateway -- ../byteplus/natgateway/nat_ip_resource_gen.go ../byteplus/natgateway/nat_ip_resource_gen_test.go
//go:generate go run generators/resource/main.go -resource bytepluscc_vke_cluster -ccschema ../service/cloudcontrol/schemas/Byteplus_VKE_Cluster.json -package vke -- ../byteplus/vke/cluster_resource_gen.go ../byteplus/vke/cluster_resource_gen_test.go
//go:generate go run generators/resource/main.go -resource bytepluscc_rdsmysql_instance -ccschema ../service/cloudcontrol/schemas/Byteplus_RDSMySQL_Instance.json -package rdsmysql -- ../byteplus/rdsmysql/instance_resource_gen.go ../byteplus/rdsmysql/instance_resource_gen_test.go
//go:generate go run generators/resource/main.go -resource bytepluscc_escloud_instance -ccschema ../service/cloudcontrol/schemas/Byteplus_ESCloud_Instance.json -package escloud -- ../byteplus/escloud/instance_resource_gen.go ../byteplus/escloud/instance_resource_gen_test.go
//go:generate go run generators/resource/main.go -resource bytepluscc_kms_key -ccschema ../service/cloudcontrol/schemas/Byteplus_KMS_Key.json -package kms -- ../byteplus/kms/key_resource_gen.go ../byteplus/kms/key_resource_gen_test.go
//go:generate go run generators/resource/main.go -resource bytepluscc_apig_gateway -ccschema ../service/cloudcontrol/schemas/Byteplus_APIG_Gateway.json -package apig -- ../byteplus/apig/gateway_resource_gen.go ../byteplus/apig/gateway_resource_gen_test.go
//go:generate go run generators/resource/main.go -resource bytepluscc_apig_custom_domain -ccschema ../service/cloudcontrol/schemas/Byteplus_APIG_CustomDomain.json -package apig -- ../byteplus/apig/custom_domain_resource_gen.go ../byteplus/apig/custom_domain_resource_gen_test.go
//go:generate go run generators/resource/main.go -resource bytepluscc_hbase_instance -ccschema ../service/cloudcontrol/schemas/Byteplus_HBase_Instance.json -package hbase -- ../byteplus/hbase/instance_resource_gen.go ../byteplus/hbase/instance_resource_gen_test.go
//go:generate go run generators/resource/main.go -resource bytepluscc_alb_certificate -ccschema ../service/cloudcontrol/schemas/Byteplus_ALB_Certificate.json -package alb -- ../byteplus/alb/certificate_resource_gen.go ../byteplus/alb/certificate_resource_gen_test.go
//go:generate go run generators/resource/main.go -resource bytepluscc_vke_addon -ccschema ../service/cloudcontrol/schemas/Byteplus_VKE_Addon.json -package vke -- ../byteplus/vke/addon_resource_gen.go ../byteplus/vke/addon_resource_gen_test.go
//go:generate go run generators/resource/main.go -resource bytepluscc_vke_node_pool -ccschema ../service/cloudcontrol/schemas/Byteplus_VKE_NodePool.json -package vke -- ../byteplus/vke/node_pool_resource_gen.go ../byteplus/vke/node_pool_resource_gen_test.go
//go:generate go run generators/resource/main.go -resource bytepluscc_vpc_security_group -ccschema ../service/cloudcontrol/schemas/Byteplus_VPC_SecurityGroup.json -package vpc -- ../byteplus/vpc/security_group_resource_gen.go ../byteplus/vpc/security_group_resource_gen_test.go
//go:generate go run generators/resource/main.go -resource bytepluscc_vpc_eni -ccschema ../service/cloudcontrol/schemas/Byteplus_VPC_ENI.json -package vpc -- ../byteplus/vpc/eni_resource_gen.go ../byteplus/vpc/eni_resource_gen_test.go
//go:generate go run generators/resource/main.go -resource bytepluscc_redis_instance -ccschema ../service/cloudcontrol/schemas/Byteplus_Redis_Instance.json -package redis -- ../byteplus/redis/instance_resource_gen.go ../byteplus/redis/instance_resource_gen_test.go
//go:generate go run generators/resource/main.go -resource bytepluscc_vepfs_instance -ccschema ../service/cloudcontrol/schemas/Byteplus_VEPFS_Instance.json -package vepfs -- ../byteplus/vepfs/instance_resource_gen.go ../byteplus/vepfs/instance_resource_gen_test.go
//go:generate go run generators/resource/main.go -resource bytepluscc_storageebs_snapshot -ccschema ../service/cloudcontrol/schemas/Byteplus_StorageEBS_Snapshot.json -package storageebs -- ../byteplus/storageebs/snapshot_resource_gen.go ../byteplus/storageebs/snapshot_resource_gen_test.go
//go:generate go run generators/resource/main.go -resource bytepluscc_kafka_topic -ccschema ../service/cloudcontrol/schemas/Byteplus_Kafka_Topic.json -package kafka -- ../byteplus/kafka/topic_resource_gen.go ../byteplus/kafka/topic_resource_gen_test.go
//go:generate go run generators/resource/main.go -resource bytepluscc_dns_zone -ccschema ../service/cloudcontrol/schemas/Byteplus_DNS_Zone.json -package dns -- ../byteplus/dns/zone_resource_gen.go ../byteplus/dns/zone_resource_gen_test.go
//go:generate go run generators/resource/main.go -resource bytepluscc_iam_project -ccschema ../service/cloudcontrol/schemas/Byteplus_IAM_Project.json -package iam -- ../byteplus/iam/project_resource_gen.go ../byteplus/iam/project_resource_gen_test.go
//go:generate go run generators/resource/main.go -resource bytepluscc_cloudidentity_user -ccschema ../service/cloudcontrol/schemas/Byteplus_CloudIdentity_User.json -package cloudidentity -- ../byteplus/cloudidentity/user_resource_gen.go ../byteplus/cloudidentity/user_resource_gen_test.go
//go:generate go run generators/resource/main.go -resource bytepluscc_bmq_instance -ccschema ../service/cloudcontrol/schemas/Byteplus_BMQ_Instance.json -package bmq -- ../byteplus/bmq/instance_resource_gen.go ../byteplus/bmq/instance_resource_gen_test.go
//go:generate go run generators/resource/main.go -resource bytepluscc_privatelink_endpoint_service -ccschema ../service/cloudcontrol/schemas/Byteplus_PrivateLink_EndpointService.json -package privatelink -- ../byteplus/privatelink/endpoint_service_resource_gen.go ../byteplus/privatelink/endpoint_service_resource_gen_test.go
//go:generate go run generators/resource/main.go -resource bytepluscc_fwcenter_dns_control_policy -ccschema ../service/cloudcontrol/schemas/Byteplus_FWCenter_DnsControlPolicy.json -package fwcenter -- ../byteplus/fwcenter/dns_control_policy_resource_gen.go ../byteplus/fwcenter/dns_control_policy_resource_gen_test.go
//go:generate go run generators/resource/main.go -resource bytepluscc_clb_rule -ccschema ../service/cloudcontrol/schemas/Byteplus_CLB_Rule.json -package clb -- ../byteplus/clb/rule_resource_gen.go ../byteplus/clb/rule_resource_gen_test.go
//go:generate go run generators/resource/main.go -resource bytepluscc_vpc_subnet -ccschema ../service/cloudcontrol/schemas/Byteplus_VPC_Subnet.json -package vpc -- ../byteplus/vpc/subnet_resource_gen.go ../byteplus/vpc/subnet_resource_gen_test.go
//go:generate go run generators/resource/main.go -resource bytepluscc_bmq_group -ccschema ../service/cloudcontrol/schemas/Byteplus_BMQ_Group.json -package bmq -- ../byteplus/bmq/group_resource_gen.go ../byteplus/bmq/group_resource_gen_test.go
//go:generate go run generators/resource/main.go -resource bytepluscc_cloudmonitor_rule -ccschema ../service/cloudcontrol/schemas/Byteplus_CloudMonitor_Rule.json -package cloudmonitor -- ../byteplus/cloudmonitor/rule_resource_gen.go ../byteplus/cloudmonitor/rule_resource_gen_test.go
//go:generate go run generators/resource/main.go -resource bytepluscc_clb_nlb_server_group -ccschema ../service/cloudcontrol/schemas/Byteplus_CLB_NLBServerGroup.json -package clb -- ../byteplus/clb/nlb_server_group_resource_gen.go ../byteplus/clb/nlb_server_group_resource_gen_test.go
//go:generate go run generators/resource/main.go -resource bytepluscc_clb_nlb_listener -ccschema ../service/cloudcontrol/schemas/Byteplus_CLB_NLBListener.json -package clb -- ../byteplus/clb/nlb_listener_resource_gen.go ../byteplus/clb/nlb_listener_resource_gen_test.go
//go:generate go run generators/resource/main.go -resource bytepluscc_clb_server_group -ccschema ../service/cloudcontrol/schemas/Byteplus_CLB_ServerGroup.json -package clb -- ../byteplus/clb/server_group_resource_gen.go ../byteplus/clb/server_group_resource_gen_test.go
//go:generate go run generators/resource/main.go -resource bytepluscc_directconnect_direct_connect_gateway -ccschema ../service/cloudcontrol/schemas/Byteplus_DirectConnect_DirectConnectGateway.json -package directconnect -- ../byteplus/directconnect/direct_connect_gateway_resource_gen.go ../byteplus/directconnect/direct_connect_gateway_resource_gen_test.go
//go:generate go run generators/resource/main.go -resource bytepluscc_vpc_eip -ccschema ../service/cloudcontrol/schemas/Byteplus_VPC_EIP.json -package vpc -- ../byteplus/vpc/eip_resource_gen.go ../byteplus/vpc/eip_resource_gen_test.go
//go:generate go run generators/resource/main.go -resource bytepluscc_vpc_route_table -ccschema ../service/cloudcontrol/schemas/Byteplus_VPC_RouteTable.json -package vpc -- ../byteplus/vpc/route_table_resource_gen.go ../byteplus/vpc/route_table_resource_gen_test.go
//go:generate go run generators/resource/main.go -resource bytepluscc_filenas_instance -ccschema ../service/cloudcontrol/schemas/Byteplus_FileNAS_Instance.json -package filenas -- ../byteplus/filenas/instance_resource_gen.go ../byteplus/filenas/instance_resource_gen_test.go

package provider

import (
	_ "github.com/byteplus-sdk/terraform-provider-bytepluscc/internal/byteplus/alb"
	_ "github.com/byteplus-sdk/terraform-provider-bytepluscc/internal/byteplus/apig"
	_ "github.com/byteplus-sdk/terraform-provider-bytepluscc/internal/byteplus/autoscaling"
	_ "github.com/byteplus-sdk/terraform-provider-bytepluscc/internal/byteplus/bmq"
	_ "github.com/byteplus-sdk/terraform-provider-bytepluscc/internal/byteplus/cdn"
	_ "github.com/byteplus-sdk/terraform-provider-bytepluscc/internal/byteplus/cen"
	_ "github.com/byteplus-sdk/terraform-provider-bytepluscc/internal/byteplus/clb"
	_ "github.com/byteplus-sdk/terraform-provider-bytepluscc/internal/byteplus/cloudidentity"
	_ "github.com/byteplus-sdk/terraform-provider-bytepluscc/internal/byteplus/cloudmonitor"
	_ "github.com/byteplus-sdk/terraform-provider-bytepluscc/internal/byteplus/cr"
	_ "github.com/byteplus-sdk/terraform-provider-bytepluscc/internal/byteplus/directconnect"
	_ "github.com/byteplus-sdk/terraform-provider-bytepluscc/internal/byteplus/dns"
	_ "github.com/byteplus-sdk/terraform-provider-bytepluscc/internal/byteplus/ecs"
	_ "github.com/byteplus-sdk/terraform-provider-bytepluscc/internal/byteplus/escloud"
	_ "github.com/byteplus-sdk/terraform-provider-bytepluscc/internal/byteplus/filenas"
	_ "github.com/byteplus-sdk/terraform-provider-bytepluscc/internal/byteplus/fwcenter"
	_ "github.com/byteplus-sdk/terraform-provider-bytepluscc/internal/byteplus/hbase"
	_ "github.com/byteplus-sdk/terraform-provider-bytepluscc/internal/byteplus/iam"
	_ "github.com/byteplus-sdk/terraform-provider-bytepluscc/internal/byteplus/kafka"
	_ "github.com/byteplus-sdk/terraform-provider-bytepluscc/internal/byteplus/kms"
	_ "github.com/byteplus-sdk/terraform-provider-bytepluscc/internal/byteplus/natgateway"
	_ "github.com/byteplus-sdk/terraform-provider-bytepluscc/internal/byteplus/organization"
	_ "github.com/byteplus-sdk/terraform-provider-bytepluscc/internal/byteplus/privatelink"
	_ "github.com/byteplus-sdk/terraform-provider-bytepluscc/internal/byteplus/rdsmysql"
	_ "github.com/byteplus-sdk/terraform-provider-bytepluscc/internal/byteplus/redis"
	_ "github.com/byteplus-sdk/terraform-provider-bytepluscc/internal/byteplus/storageebs"
	_ "github.com/byteplus-sdk/terraform-provider-bytepluscc/internal/byteplus/vefaas"
	_ "github.com/byteplus-sdk/terraform-provider-bytepluscc/internal/byteplus/vepfs"
	_ "github.com/byteplus-sdk/terraform-provider-bytepluscc/internal/byteplus/vke"
	_ "github.com/byteplus-sdk/terraform-provider-bytepluscc/internal/byteplus/vpc"
)
