// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0

// Code generated by generators/schema/main.go; DO NOT EDIT.
//go:generate go run generators/resource/main.go -resource bytepluscc_ecs_image -ccschema ../service/cloudcontrol/schemas/Byteplus_ECS_Image.json -package ecs -- ../byteplus/ecs/image_resource_gen.go ../byteplus/ecs/image_resource_gen_test.go
//go:generate go run generators/resource/main.go -resource bytepluscc_clb_listener -ccschema ../service/cloudcontrol/schemas/Byteplus_CLB_Listener.json -package clb -- ../byteplus/clb/listener_resource_gen.go ../byteplus/clb/listener_resource_gen_test.go
//go:generate go run generators/resource/main.go -resource bytepluscc_vpc_vpc -ccschema ../service/cloudcontrol/schemas/Byteplus_VPC_VPC.json -package vpc -- ../byteplus/vpc/vpc_resource_gen.go ../byteplus/vpc/vpc_resource_gen_test.go
//go:generate go run generators/resource/main.go -resource bytepluscc_storageebs_volume -ccschema ../service/cloudcontrol/schemas/Byteplus_StorageEBS_Volume.json -package storageebs -- ../byteplus/storageebs/volume_resource_gen.go ../byteplus/storageebs/volume_resource_gen_test.go
//go:generate go run generators/resource/main.go -resource bytepluscc_alb_listener -ccschema ../service/cloudcontrol/schemas/Byteplus_ALB_Listener.json -package alb -- ../byteplus/alb/listener_resource_gen.go ../byteplus/alb/listener_resource_gen_test.go
//go:generate go run generators/resource/main.go -resource bytepluscc_cr_repository -ccschema ../service/cloudcontrol/schemas/Byteplus_CR_Repository.json -package cr -- ../byteplus/cr/repository_resource_gen.go ../byteplus/cr/repository_resource_gen_test.go
//go:generate go run generators/resource/main.go -resource bytepluscc_autoscaling_scaling_configuration -ccschema ../service/cloudcontrol/schemas/Byteplus_AutoScaling_ScalingConfiguration.json -package autoscaling -- ../byteplus/autoscaling/scaling_configuration_resource_gen.go ../byteplus/autoscaling/scaling_configuration_resource_gen_test.go
//go:generate go run generators/resource/main.go -resource bytepluscc_ecs_instance -ccschema ../service/cloudcontrol/schemas/Byteplus_ECS_Instance.json -package ecs -- ../byteplus/ecs/instance_resource_gen.go ../byteplus/ecs/instance_resource_gen_test.go
//go:generate go run generators/resource/main.go -resource bytepluscc_vke_permission -ccschema ../service/cloudcontrol/schemas/Byteplus_VKE_Permission.json -package vke -- ../byteplus/vke/permission_resource_gen.go ../byteplus/vke/permission_resource_gen_test.go
//go:generate go run generators/resource/main.go -resource bytepluscc_vefaas_sandbox -ccschema ../service/cloudcontrol/schemas/Byteplus_VEFAAS_Sandbox.json -package vefaas -- ../byteplus/vefaas/sandbox_resource_gen.go ../byteplus/vefaas/sandbox_resource_gen_test.go
//go:generate go run generators/resource/main.go -resource bytepluscc_vefaas_kafka_trigger -ccschema ../service/cloudcontrol/schemas/Byteplus_VEFAAS_KafkaTrigger.json -package vefaas -- ../byteplus/vefaas/kafka_trigger_resource_gen.go ../byteplus/vefaas/kafka_trigger_resource_gen_test.go
//go:generate go run generators/resource/main.go -resource bytepluscc_cdn_share_config -ccschema ../service/cloudcontrol/schemas/Byteplus_CDN_ShareConfig.json -package cdn -- ../byteplus/cdn/share_config_resource_gen.go ../byteplus/cdn/share_config_resource_gen_test.go
//go:generate go run generators/resource/main.go -resource bytepluscc_apig_upstream -ccschema ../service/cloudcontrol/schemas/Byteplus_APIG_Upstream.json -package apig -- ../byteplus/apig/upstream_resource_gen.go ../byteplus/apig/upstream_resource_gen_test.go
//go:generate go run generators/resource/main.go -resource bytepluscc_apig_upstream_source -ccschema ../service/cloudcontrol/schemas/Byteplus_APIG_UpstreamSource.json -package apig -- ../byteplus/apig/upstream_source_resource_gen.go ../byteplus/apig/upstream_source_resource_gen_test.go
//go:generate go run generators/resource/main.go -resource bytepluscc_apig_gateway_service -ccschema ../service/cloudcontrol/schemas/Byteplus_APIG_GatewayService.json -package apig -- ../byteplus/apig/gateway_service_resource_gen.go ../byteplus/apig/gateway_service_resource_gen_test.go
//go:generate go run generators/resource/main.go -resource bytepluscc_iam_policy -ccschema ../service/cloudcontrol/schemas/Byteplus_IAM_Policy.json -package iam -- ../byteplus/iam/policy_resource_gen.go ../byteplus/iam/policy_resource_gen_test.go
//go:generate go run generators/resource/main.go -resource bytepluscc_iam_role -ccschema ../service/cloudcontrol/schemas/Byteplus_IAM_Role.json -package iam -- ../byteplus/iam/role_resource_gen.go ../byteplus/iam/role_resource_gen_test.go
//go:generate go run generators/resource/main.go -resource bytepluscc_iam_user -ccschema ../service/cloudcontrol/schemas/Byteplus_IAM_User.json -package iam -- ../byteplus/iam/user_resource_gen.go ../byteplus/iam/user_resource_gen_test.go
//go:generate go run generators/resource/main.go -resource bytepluscc_clb_listener -ccschema ../service/cloudcontrol/schemas/Byteplus_CLB_Listener.json -package clb -- ../byteplus/clb/listener_resource_gen.go ../byteplus/clb/listener_resource_gen_test.go
//go:generate go run generators/resource/main.go -resource bytepluscc_natgateway_ngw -ccschema ../service/cloudcontrol/schemas/Byteplus_NatGateway_NGW.json -package natgateway -- ../byteplus/natgateway/ngw_resource_gen.go ../byteplus/natgateway/ngw_resource_gen_test.go
//go:generate go run generators/resource/main.go -resource bytepluscc_organization_unit -ccschema ../service/cloudcontrol/schemas/Byteplus_Organization_Unit.json -package organization -- ../byteplus/organization/unit_resource_gen.go ../byteplus/organization/unit_resource_gen_test.go
//go:generate go run generators/resource/main.go -resource bytepluscc_rdsmysql_db_account -ccschema ../service/cloudcontrol/schemas/Byteplus_RDSMySQL_DBAccount.json -package rdsmysql -- ../byteplus/rdsmysql/db_account_resource_gen.go ../byteplus/rdsmysql/db_account_resource_gen_test.go
//go:generate go run generators/resource/main.go -resource bytepluscc_autoscaling_scaling_group -ccschema ../service/cloudcontrol/schemas/Byteplus_AutoScaling_ScalingGroup.json -package autoscaling -- ../byteplus/autoscaling/scaling_group_resource_gen.go ../byteplus/autoscaling/scaling_group_resource_gen_test.go
//go:generate go run generators/resource/main.go -resource bytepluscc_cen_cen -ccschema ../service/cloudcontrol/schemas/Byteplus_CEN_CEN.json -package cen -- ../byteplus/cen/cen_resource_gen.go ../byteplus/cen/cen_resource_gen_test.go
//go:generate go run generators/resource/main.go -resource bytepluscc_natgateway_snatentry -ccschema ../service/cloudcontrol/schemas/Byteplus_NatGateway_Snatentry.json -package natgateway -- ../byteplus/natgateway/snatentry_resource_gen.go ../byteplus/natgateway/snatentry_resource_gen_test.go
//go:generate go run generators/resource/main.go -resource bytepluscc_natgateway_dnatentry -ccschema ../service/cloudcontrol/schemas/Byteplus_NatGateway_Dnatentry.json -package natgateway -- ../byteplus/natgateway/dnatentry_resource_gen.go ../byteplus/natgateway/dnatentry_resource_gen_test.go
//go:generate go run generators/resource/main.go -resource bytepluscc_natgateway_nat_ip -ccschema ../service/cloudcontrol/schemas/Byteplus_NatGateway_NatIp.json -package natgateway -- ../byteplus/natgateway/nat_ip_resource_gen.go ../byteplus/natgateway/nat_ip_resource_gen_test.go

package provider

import (
	_ "github.com/byteplus-sdk/terraform-provider-bytepluscc/internal/byteplus/alb"
	_ "github.com/byteplus-sdk/terraform-provider-bytepluscc/internal/byteplus/apig"
	_ "github.com/byteplus-sdk/terraform-provider-bytepluscc/internal/byteplus/autoscaling"
	_ "github.com/byteplus-sdk/terraform-provider-bytepluscc/internal/byteplus/cdn"
	_ "github.com/byteplus-sdk/terraform-provider-bytepluscc/internal/byteplus/cen"
	_ "github.com/byteplus-sdk/terraform-provider-bytepluscc/internal/byteplus/clb"
	_ "github.com/byteplus-sdk/terraform-provider-bytepluscc/internal/byteplus/cr"
	_ "github.com/byteplus-sdk/terraform-provider-bytepluscc/internal/byteplus/ecs"
	_ "github.com/byteplus-sdk/terraform-provider-bytepluscc/internal/byteplus/iam"
	_ "github.com/byteplus-sdk/terraform-provider-bytepluscc/internal/byteplus/natgateway"
	_ "github.com/byteplus-sdk/terraform-provider-bytepluscc/internal/byteplus/organization"
	_ "github.com/byteplus-sdk/terraform-provider-bytepluscc/internal/byteplus/rdsmysql"
	_ "github.com/byteplus-sdk/terraform-provider-bytepluscc/internal/byteplus/storageebs"
	_ "github.com/byteplus-sdk/terraform-provider-bytepluscc/internal/byteplus/vefaas"
	_ "github.com/byteplus-sdk/terraform-provider-bytepluscc/internal/byteplus/vke"
	_ "github.com/byteplus-sdk/terraform-provider-bytepluscc/internal/byteplus/vpc"
)
