// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0

// Code generated by generators/schema/main.go; DO NOT EDIT.
//go:generate go run generators/singular-data-source/main.go -data-source bytepluscc_ecs_image -ccschema ../service/cloudcontrol/schemas/Volcengine_ECS_Image.json -package ecs ../byteplus/ecs/image_singular_data_source_gen.go ../byteplus/ecs/image_singular_data_source_gen_test.go

package provider

import (
	_ "github.com/byteplus/terraform-provider-bytepluscc/internal/byteplus/ecs"
)
