// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0

// Code generated by generators/singular-data-source/main.go; DO NOT EDIT.

package bmq

import (
	"context"

	"github.com/byteplus-sdk/terraform-provider-bytepluscc/internal/generic"
	"github.com/byteplus-sdk/terraform-provider-bytepluscc/internal/registry"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func init() {
	registry.AddDataSourceFactory("bytepluscc_bmq_group", groupDataSource)
}

// groupDataSource returns the Terraform bytepluscc_bmq_group data source.
// This Terraform data source corresponds to the Cloud Control Byteplus::BMQ::Group resource.
func groupDataSource(ctx context.Context) (datasource.DataSource, error) {
	attributes := map[string]schema.Attribute{ /*START SCHEMA*/
		// Property: CreatedTime
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Consumer Group creation time.",
		//	  "type": "string"
		//	}
		"created_time": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Consumer Group creation time.",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: Description
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Consumer Group description.",
		//	  "type": "string"
		//	}
		"description": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Consumer Group description.",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: GroupId
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Consumer Group ID.",
		//	  "type": "string"
		//	}
		"group_id": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Consumer Group ID.",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: GroupName
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Set the Consumer Group name manually. Constraints: Only lowercase English letters, numbers, underscores, and hyphens (-) are allowed. Length must be 3–64 characters.",
		//	  "maxLength": 64,
		//	  "minLength": 3,
		//	  "type": "string"
		//	}
		"group_name": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Set the Consumer Group name manually. Constraints: Only lowercase English letters, numbers, underscores, and hyphens (-) are allowed. Length must be 3–64 characters.",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: InstanceId
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "BMQ instance ID.",
		//	  "type": "string"
		//	}
		"instance_id": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "BMQ instance ID.",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: OwnerId
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "User ID associated with the Consumer Group.",
		//	  "type": "string"
		//	}
		"owner_id": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "User ID associated with the Consumer Group.",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: OwnerName
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Name of the user associated with the Consumer Group.",
		//	  "type": "string"
		//	}
		"owner_name": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Name of the user associated with the Consumer Group.",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: ResetInfo
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Reset consumption position information.",
		//	  "properties": {
		//	    "OffsetType": {
		//	      "description": "This parameter is required when the reset mode is OFFSET. Specifies the reference consumption position for re-consuming. Options are: EARLIEST: The reference position is the earliest consumption point. CURRENT: The reference position is the current consumption point. LATEST: The reference position is the latest consumption point.",
		//	      "type": "string"
		//	    },
		//	    "PartitionId": {
		//	      "description": "Partition number.",
		//	      "type": "integer"
		//	    },
		//	    "ResetBy": {
		//	      "description": "Reset mode. Options are: TIMESTAMP: Reset the consumption position based on a specific time point. Specify a past or future time, and jump directly to the position at that time to start consuming. OFFSET: Reset the consumption position based on a specified offset. Start consuming from the specified position, and you can use the offsetType parameter to specify the offset.",
		//	      "type": "string"
		//	    },
		//	    "ResetValue": {
		//	      "description": "Reset value. If the reset mode is TIMESTAMP, this value is the time point for re-consuming messages, for example, 1722224612000. If the reset mode is OFFSET, this value is the relative offset from the reference position specified in OffsetType, for example, 100.",
		//	      "format": "int64",
		//	      "type": "integer"
		//	    },
		//	    "TopicId": {
		//	      "description": "Topic ID。",
		//	      "type": "string"
		//	    }
		//	  },
		//	  "type": "object"
		//	}
		"reset_info": schema.SingleNestedAttribute{ /*START ATTRIBUTE*/
			Attributes: map[string]schema.Attribute{ /*START SCHEMA*/
				// Property: OffsetType
				"offset_type": schema.StringAttribute{ /*START ATTRIBUTE*/
					Description: "This parameter is required when the reset mode is OFFSET. Specifies the reference consumption position for re-consuming. Options are: EARLIEST: The reference position is the earliest consumption point. CURRENT: The reference position is the current consumption point. LATEST: The reference position is the latest consumption point.",
					Computed:    true,
				}, /*END ATTRIBUTE*/
				// Property: PartitionId
				"partition_id": schema.Int64Attribute{ /*START ATTRIBUTE*/
					Description: "Partition number.",
					Computed:    true,
				}, /*END ATTRIBUTE*/
				// Property: ResetBy
				"reset_by": schema.StringAttribute{ /*START ATTRIBUTE*/
					Description: "Reset mode. Options are: TIMESTAMP: Reset the consumption position based on a specific time point. Specify a past or future time, and jump directly to the position at that time to start consuming. OFFSET: Reset the consumption position based on a specified offset. Start consuming from the specified position, and you can use the offsetType parameter to specify the offset.",
					Computed:    true,
				}, /*END ATTRIBUTE*/
				// Property: ResetValue
				"reset_value": schema.Int64Attribute{ /*START ATTRIBUTE*/
					Description: "Reset value. If the reset mode is TIMESTAMP, this value is the time point for re-consuming messages, for example, 1722224612000. If the reset mode is OFFSET, this value is the relative offset from the reference position specified in OffsetType, for example, 100.",
					Computed:    true,
				}, /*END ATTRIBUTE*/
				// Property: TopicId
				"topic_id": schema.StringAttribute{ /*START ATTRIBUTE*/
					Description: "Topic ID。",
					Computed:    true,
				}, /*END ATTRIBUTE*/
			}, /*END SCHEMA*/
			Description: "Reset consumption position information.",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: Status
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Consumer Group status.",
		//	  "type": "string"
		//	}
		"status": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Consumer Group status.",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: TopicInfos
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Topic list.",
		//	  "insertionOrder": false,
		//	  "items": {
		//	    "properties": {
		//	      "CreateTime": {
		//	        "description": "Topic creation time.",
		//	        "type": "string"
		//	      },
		//	      "Description": {
		//	        "description": "Topic description.",
		//	        "type": "string"
		//	      },
		//	      "Lag": {
		//	        "description": "Number of unconsumed messages in the Topic.",
		//	        "format": "int64",
		//	        "type": "integer"
		//	      },
		//	      "PartitionInfos": {
		//	        "description": "Partition list.",
		//	        "insertionOrder": false,
		//	        "items": {
		//	          "properties": {
		//	            "CurrentOffset": {
		//	              "description": "Current consumption position.",
		//	              "format": "int64",
		//	              "type": "integer"
		//	            },
		//	            "GroupName": {
		//	              "description": "Name of the Consumer Group.",
		//	              "type": "string"
		//	            },
		//	            "Lag": {
		//	              "description": "Number of unconsumed messages in the partition.",
		//	              "format": "int64",
		//	              "type": "integer"
		//	            },
		//	            "LatestOffset": {
		//	              "description": "Latest consumption position.",
		//	              "format": "int64",
		//	              "type": "integer"
		//	            },
		//	            "PartitionId": {
		//	              "description": "Partition number.",
		//	              "type": "integer"
		//	            },
		//	            "TopicName": {
		//	              "description": "Name of the Topic subscribed by the Consumer Group.",
		//	              "type": "string"
		//	            }
		//	          },
		//	          "type": "object"
		//	        },
		//	        "type": "array",
		//	        "uniqueItems": true
		//	      },
		//	      "Partitions": {
		//	        "description": "Number of Topic partitions.",
		//	        "type": "integer"
		//	      },
		//	      "Retention": {
		//	        "description": "Retention period of data in the Topic, in hours.",
		//	        "type": "integer"
		//	      },
		//	      "Status": {
		//	        "description": "Topic status.",
		//	        "type": "string"
		//	      },
		//	      "TopicId": {
		//	        "description": "Topic ID。",
		//	        "type": "string"
		//	      },
		//	      "TopicName": {
		//	        "description": "Topic name.",
		//	        "type": "string"
		//	      }
		//	    },
		//	    "type": "object"
		//	  },
		//	  "type": "array",
		//	  "uniqueItems": true
		//	}
		"topic_infos": schema.SetNestedAttribute{ /*START ATTRIBUTE*/
			NestedObject: schema.NestedAttributeObject{ /*START NESTED OBJECT*/
				Attributes: map[string]schema.Attribute{ /*START SCHEMA*/
					// Property: CreateTime
					"create_time": schema.StringAttribute{ /*START ATTRIBUTE*/
						Description: "Topic creation time.",
						Computed:    true,
					}, /*END ATTRIBUTE*/
					// Property: Description
					"description": schema.StringAttribute{ /*START ATTRIBUTE*/
						Description: "Topic description.",
						Computed:    true,
					}, /*END ATTRIBUTE*/
					// Property: Lag
					"lag": schema.Int64Attribute{ /*START ATTRIBUTE*/
						Description: "Number of unconsumed messages in the Topic.",
						Computed:    true,
					}, /*END ATTRIBUTE*/
					// Property: PartitionInfos
					"partition_infos": schema.SetNestedAttribute{ /*START ATTRIBUTE*/
						NestedObject: schema.NestedAttributeObject{ /*START NESTED OBJECT*/
							Attributes: map[string]schema.Attribute{ /*START SCHEMA*/
								// Property: CurrentOffset
								"current_offset": schema.Int64Attribute{ /*START ATTRIBUTE*/
									Description: "Current consumption position.",
									Computed:    true,
								}, /*END ATTRIBUTE*/
								// Property: GroupName
								"group_name": schema.StringAttribute{ /*START ATTRIBUTE*/
									Description: "Name of the Consumer Group.",
									Computed:    true,
								}, /*END ATTRIBUTE*/
								// Property: Lag
								"lag": schema.Int64Attribute{ /*START ATTRIBUTE*/
									Description: "Number of unconsumed messages in the partition.",
									Computed:    true,
								}, /*END ATTRIBUTE*/
								// Property: LatestOffset
								"latest_offset": schema.Int64Attribute{ /*START ATTRIBUTE*/
									Description: "Latest consumption position.",
									Computed:    true,
								}, /*END ATTRIBUTE*/
								// Property: PartitionId
								"partition_id": schema.Int64Attribute{ /*START ATTRIBUTE*/
									Description: "Partition number.",
									Computed:    true,
								}, /*END ATTRIBUTE*/
								// Property: TopicName
								"topic_name": schema.StringAttribute{ /*START ATTRIBUTE*/
									Description: "Name of the Topic subscribed by the Consumer Group.",
									Computed:    true,
								}, /*END ATTRIBUTE*/
							}, /*END SCHEMA*/
						}, /*END NESTED OBJECT*/
						Description: "Partition list.",
						Computed:    true,
					}, /*END ATTRIBUTE*/
					// Property: Partitions
					"partitions": schema.Int64Attribute{ /*START ATTRIBUTE*/
						Description: "Number of Topic partitions.",
						Computed:    true,
					}, /*END ATTRIBUTE*/
					// Property: Retention
					"retention": schema.Int64Attribute{ /*START ATTRIBUTE*/
						Description: "Retention period of data in the Topic, in hours.",
						Computed:    true,
					}, /*END ATTRIBUTE*/
					// Property: Status
					"status": schema.StringAttribute{ /*START ATTRIBUTE*/
						Description: "Topic status.",
						Computed:    true,
					}, /*END ATTRIBUTE*/
					// Property: TopicId
					"topic_id": schema.StringAttribute{ /*START ATTRIBUTE*/
						Description: "Topic ID。",
						Computed:    true,
					}, /*END ATTRIBUTE*/
					// Property: TopicName
					"topic_name": schema.StringAttribute{ /*START ATTRIBUTE*/
						Description: "Topic name.",
						Computed:    true,
					}, /*END ATTRIBUTE*/
				}, /*END SCHEMA*/
			}, /*END NESTED OBJECT*/
			Description: "Topic list.",
			Computed:    true,
		}, /*END ATTRIBUTE*/
	} /*END SCHEMA*/

	attributes["id"] = schema.StringAttribute{
		Description: "Uniquely identifies the resource.",
		Required:    true,
	}

	schema := schema.Schema{
		Description: "Data Source schema for Byteplus::BMQ::Group",
		Attributes:  attributes,
	}

	var opts generic.DataSourceOptions

	opts = opts.WithCloudControlTypeName("Byteplus::BMQ::Group").WithTerraformTypeName("bytepluscc_bmq_group")
	opts = opts.WithTerraformSchema(schema)
	opts = opts.WithAttributeNameMap(map[string]string{
		"create_time":     "CreateTime",
		"created_time":    "CreatedTime",
		"current_offset":  "CurrentOffset",
		"description":     "Description",
		"group_id":        "GroupId",
		"group_name":      "GroupName",
		"instance_id":     "InstanceId",
		"lag":             "Lag",
		"latest_offset":   "LatestOffset",
		"offset_type":     "OffsetType",
		"owner_id":        "OwnerId",
		"owner_name":      "OwnerName",
		"partition_id":    "PartitionId",
		"partition_infos": "PartitionInfos",
		"partitions":      "Partitions",
		"reset_by":        "ResetBy",
		"reset_info":      "ResetInfo",
		"reset_value":     "ResetValue",
		"retention":       "Retention",
		"status":          "Status",
		"topic_id":        "TopicId",
		"topic_infos":     "TopicInfos",
		"topic_name":      "TopicName",
	})

	v, err := generic.NewSingularDataSource(ctx, opts...)

	if err != nil {
		return nil, err
	}

	return v, nil
}
