// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0

// Code generated by generators/singular-data-source/main.go; DO NOT EDIT.

package clb

import (
	"context"

	"github.com/byteplus-sdk/terraform-provider-bytepluscc/internal/generic"
	"github.com/byteplus-sdk/terraform-provider-bytepluscc/internal/registry"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func init() {
	registry.AddDataSourceFactory("bytepluscc_clb_check_log_project", checkLogProjectDataSource)
}

// checkLogProjectDataSource returns the Terraform bytepluscc_clb_check_log_project data source.
// This Terraform data source corresponds to the Cloud Control Byteplus::CLB::CheckLogProject resource.
func checkLogProjectDataSource(ctx context.Context) (datasource.DataSource, error) {
	attributes := map[string]schema.Attribute{ /*START SCHEMA*/
		// Property: LogProjectId
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Log Project ID.",
		//	  "type": "string"
		//	}
		"log_project_id": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Log Project ID.",
			Computed:    true,
		}, /*END ATTRIBUTE*/
	} /*END SCHEMA*/

	attributes["id"] = schema.StringAttribute{
		Description: "Uniquely identifies the resource.",
		Required:    true,
	}

	schema := schema.Schema{
		Description: "Data Source schema for Byteplus::CLB::CheckLogProject",
		Attributes:  attributes,
	}

	var opts generic.DataSourceOptions

	opts = opts.WithCloudControlTypeName("Byteplus::CLB::CheckLogProject").WithTerraformTypeName("bytepluscc_clb_check_log_project")
	opts = opts.WithTerraformSchema(schema)
	opts = opts.WithAttributeNameMap(map[string]string{
		"log_project_id": "LogProjectId",
	})

	v, err := generic.NewSingularDataSource(ctx, opts...)

	if err != nil {
		return nil, err
	}

	return v, nil
}
