// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0

// Code generated by generators/singular-data-source/main.go; DO NOT EDIT.

package clb_test

import (
	"fmt"
	"regexp"
	"testing"

	"github.com/byteplus-sdk/terraform-provider-bytepluscc/internal/acctest"
	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
)

func TestAccByteplusCLBCLBDataSource_basic(t *testing.T) {
	td := acctest.NewTestData(t, "Byteplus::CLB::CLB", "bytepluscc_clb_clb", "test")

	td.DataSourceTest(t, []resource.TestStep{
		{
			Config: td.DataSourceWithEmptyResourceConfig(),
			Check: resource.ComposeTestCheckFunc(
				resource.TestCheckResourceAttrPair(fmt.Sprintf("data.%s", td.ResourceName), "id", td.ResourceName, "id"),
				resource.TestCheckResourceAttrPair(fmt.Sprintf("data.%s", td.ResourceName), "arn", td.ResourceName, "arn"),
			),
		},
	})
}

func TestAccByteplusCLBCLBDataSource_NonExistent(t *testing.T) {
	td := acctest.NewTestData(t, "Byteplus::CLB::CLB", "bytepluscc_clb_clb", "test")

	td.DataSourceTest(t, []resource.TestStep{
		{
			Config:      td.DataSourceWithNonExistentIDConfig(),
			ExpectError: regexp.MustCompile("Not Found"),
		},
	})
}
